
stock AfficherCredits(playerid)
{
	SendClientMessage(playerid,0xB86A0AFF,"==============================================================");	
	SendClientMessage(playerid,0x3A6715FF,"Raphy963 : Création du système d'administration");
	SendClientMessage(playerid,0xB86A0AFF,"==============================================================");
	print("work");
	return 1;
}
stock FSLoad()
{
	print("\n\n\n=============================================================================");
	print("|                  Kleptyc's Administration System   V0.1                   |");
	print("|                   Créé par : raphy963(Kleptyc)                      	    |");
	print("|                                                                           |");
	print("|                Merci de ne pas enlever les crédits!                       |");
	print("|                                                                      2012 |");
	print("=============================================================================");
	return 1;
}

